### ISSUE TITLE
Revocation Scripts for Keylime

### ISSUE THREAD

**Issue by lukehinds** [redhat-et/edge-security-demo#11]

**Comment by mpeters** [comment]
The following OC commands should work to cordon off the node and have k8s migrate the workload to other nodes:

```
oc adm cordon mpeters-okd-zxrh5-worker-mrbw7
oc adm drain mpeters-okd-zxrh5-worker-mrbw7 --force=true --ignore-daemonsets --delete-local-data
```

Then when the node is ready to be put back in circulation

```
oc adm uncordon mpeters-okd-zxrh5-worker-mrbw7
```

**Comment by mpeters** [comment]
https://github.com/redhat-et/edge-security-demo/pull/28
